---
# REM: maunally install before using with
# $ ansible-galaxy install -r requirements.yml

- src: https://github.com/dheles/ansible-role-login-user
  name: login-user

- src: https://github.com/dheles/ansible-role-secure-ssh
  name: secure-ssh

- src: https://github.com/dheles/deploy-keys-ansible-role
  name: deploy-keys

- src: https://github.com/dheles/ansible-role-java.git
  name: java

- src: https://github.com/dheles/ansible-role-apache.git
  name: apache

- src: https://github.com/dheles/ansible-role-passenger.git
  name: passenger

- src: https://github.com/dheles/ansible-chruby.git
  name: chruby

- src: https://github.com/jhu-sheridan-libraries/ansible-role-mysql
  name: mysql

- src: https://github.com/dheles/jetty-ansible-role
  name: jetty
