# pull-reserves vars
pull_reserves_app_user:       "{{ app_user }}"
pull_reserves_app_name:       "catalyst-pull-reserves"
pull_reserves_app_repo:       "https://github.com/jhu-sheridan-libraries/catalyst-pull-reserves.git"
# every 5 minutes between the hours of 6am and 11pm; UTC?
# pull_reserves_cron_minute:    "*/5"
# pull_reserves_cron_hour:      "6-23"
pull_reserves_cron_command: "/bin/bash -lc 'cd {{ service_deploy_dir }} && bundle exec ruby ./pull_reserves.rb >> {{ service_log_file }} 2>&1'"
pull_reserves_config_files:
- template:                 "templates/pull_reserves_dotenv.j2"
  dest:                     "{{ service_deploy_dir }}/.env"
