# REM: if you are looking for passwords or other variables
# that vary from dev to stage to prod, check the other subfolders

# setup vars
project:                      "catalyst-ansible"
version:                      "0.3.0"
login_user:                   "deploy"

# ssh vars
ssh_port: 22
# uncomment after first run (if not 22):
# ansible_ssh_port: "{{ ssh_port }}"

mode:                         "deploy" # dev || deploy

app_repo:                     "git@github.com:jhu-sheridan-libraries/blacklight-rails.git" #"https://github.com/jhu-sheridan-libraries/blacklight-rails"
app_branch:                   "ansibilize"
app_name:                     "catalyst"
app_user:                     "{{ app_name }}"
app_group:                    "{{ app_user }}"
base_deploy_dir:              "/opt"
deploy_dir:                   "{{ base_deploy_dir }}/{{ app_name }}"

# deploy keys vars
deploy_private_key:           "{{ vault_deploy_private_key }}"
deploy_public_key:            "{{ vault_deploy_public_key }}"
deploy_user:                  "{{ login_user }}"
deploy_key_name:              "catalyst_deploy_key"
deploy_key_full_path:         "/home/{{ deploy_user }}/.ssh/{{ deploy_key_name }}"

# rails vars
rails_env:                    "development"
# NOTE: need to keep in sync with application Gemfile
# TODO: test updating to recent version
rails_version:                "4.2.4"
secret_key_base:              "" # will be generated

# apache vars
apache_remove_welcome:        true
apache_https:                 true
# TODO: only works for CentOS. + needs refactoring
apache_service:               "httpd"
apache_config_file:           "/etc/{{ apache_service }}/conf.d/01_{{ hostname }}.conf"
# NOTE: use this to override the whole apache config template
# apache_config_template:     "templates/apache.conf.j2"
apache_http_redirect_marker:  "http redirect"

# passenger vars
# TODO: adopt and move up
update_packages:        false
# NOTE: use this to override the passenger virtualhost sub-template
# passenger_virtualhost_template:     "templates/passenger_virtualhost.j2"
