# REM: if you are looking for passwords or other variables
# that vary from dev to stage to prod, check the other subfolders

# setup vars
project:          "catalyst-ansible"
version:          "0.2.0"
login_user:       "deploy"

# ssh vars
ssh_port: 22
# uncomment after first run (if not 22):
# ansible_ssh_port: "{{ ssh_port }}"

mode:             "dev" # dev || deploy

app_repo:         "https://github.com/jhu-sheridan-libraries/blacklight-rails"
app_branch:       "master"
app_name:         "catalyst"
app_user:         "{{ app_name }}"
app_group:        "{{ app_user }}"
base_deploy_dir:  "/opt"
deploy_dir:       "{{ base_deploy_dir }}/{{ app_name }}"
