# setup vars
mode:                         "deploy" # dev || deploy

# ruby vars
chruby_ruby_version:          "jruby-9.1.12.0"

app_name:                     "pull_reserves"
app_user:                     "catalyst"
app_group:                    "{{ app_user }}"
download_dir:                 "/home/{{ login_user }}/{{ app_name }}"

# rails vars
rails_env:                    "production"
