# services vars
# NOTE: anything set here will override environment-specific values

mode:                         "deploy" # dev || deploy

# ruby vars
# chruby_ruby_version:          "jruby-9.1.12.0"
# service_ruby_version:         "jruby-1.7.4" # NOTE: at present, jruby-1.7.4 is unavailable from the official source
service_ruby_version:         "jruby-9.1.14.0"
service_ruby_path:            "/opt/rubies/{{ service_ruby_version }}"
chruby_ruby_version:          "{{ service_ruby_version }}"

app_user:                     "catalyst"
app_group:                    "{{ app_user }}"
download_dir:                 "/home/{{ login_user }}/{{ app_name }}"

# rails vars
rails_env:                    "production"

# traject vars
traject_app_name:             "traject"
traject_app_repo:             "https://github.com/jhu-sheridan-libraries/catalyst-traject.git"
traject_cron_command:         "/bin/bash -lc 'cd {{ service_deploy_dir }} && bundle exec rake horizon:mass_index >> {{ service_log_file }} 2>&1'"
traject_config_files:
  - template:                 "templates/traject_dotenv.j2"
    dest:                     "{{ service_deploy_dir }}/.env"
# NOTE: set in the group_vars for the environment:
# DON"T set them here or they will override those environment-specific values
#
# REQUIRED
# traject_cron_minute:
# traject_cron_hour:
# solr_replicate_master:
# solr_url_to_index:
# OPTIONAL
# only_bib:
# first_bib:
# last_bib:


# pull-reserves vars
pull_reserves_app_name:       "pull_reserves"
pull_reserves_app_repo:       "https://github.com/jhu-sheridan-libraries/catalyst-pull-reserves.git"
# every 5 minutes between the hours of 6am and 11pm; UTC?
# pull_reserves_cron_minute:    "*/5"
# pull_reserves_cron_hour:      "6-23"
pull_reserves_cron_command: "/bin/bash -lc 'cd {{ service_deploy_dir }} && bundle exec ruby ./pull_reserves.rb >> {{ service_log_file }} 2>&1'"
pull_reserves_config_files:
- template:                 "templates/database.yml.j2"
  dest:                     "{{ service_deploy_dir }}/config/database.yml"
- template:                 "templates/horizon.yml.j2"
  dest:                     "{{ service_deploy_dir }}/config/horizon.yml"
