---
- name: build catalyst
  hosts: build
  become: true

  tasks:
  - name: install required packages
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - git
      - nodejs
