- name: install catalyst prereqs
  hosts: catalyst

  roles:
  - { role: java,         tags: ['java'],   become: true }
  - { role: chruby,       tags: ['chruby'], become: true  }
  - { role: apache,       tags: ['apache'] }
  - { role: passenger,    tags: ['passenger'] }
  - { role: deploy-keys,  tags: ['deploy-keys'] }
  - { role: shib,         tags: ['shib'] }
  - { role: firewalld,    tags: ['firewalld'], become: true}
  - { role: logrotate,    tags: ['logrotate'] }
