---
- name: install catalyst rails application
  hosts: catalyst

  roles:
  - { role: deploy-keys }

  tasks:
  - name: install required packages
    package:
      name: "{{ item }}"
      state: present
    become: true
    with_items:
      - git
      - nodejs

  - name: configure application user
    include: configure_app_user.yml

  - name: make sure deploy dir exists
    file:
      path: "{{ deploy_dir }}"
      owner: "{{ app_user }}"
      group: "{{ app_group }}"
      state: directory
      recurse: true
    become: true

  - name: get application from repo
    git:
      repo: "{{ app_repo }}"
      dest: "{{ deploy_dir }}"
      version: "{{ app_branch | default('HEAD') }}"
      key_file: "{{ deploy_key_full_path }}"
      ssh_opts: "-o StrictHostKeyChecking=no"
