---
- name: install catalyst rails application
  hosts: catalyst

  roles:
  - { role: deploy-keys }

  tasks:
  - name: install required packages
    package:
      name: "{{ item }}"
      state: present
    become: true
    with_items:
      - git
      - nodejs
      - "@Development tools"
      - mysql-devel

  - name: configure application user
    include: configure_app_user.yml

  - name: make sure deploy dir exists
    file:
      path: "{{ deploy_dir }}"
      owner: "{{ app_user }}"
      group: "{{ app_group }}"
      state: directory
      recurse: true
    become: true

  - name: get application from repo
    git:
      repo: "{{ app_repo }}"
      dest: "{{ deploy_dir }}"
      version: "{{ app_branch | default('HEAD') }}"
      key_file: "{{ deploy_key_full_path }}"
      ssh_opts: "-o StrictHostKeyChecking=no"

  - name: configure bundle install based on mode
    set_fact:
      deployment_mode: false
  - set_fact:
      deployment_mode: true
    when: mode == "deploy"

  # NOTE: don't install spring in production environments:
  # https://github.com/projecthydra/hydra-head/issues/201
  - name: adjust for the rails environment
    set_fact:
      exclude: "development, test"
    when: rails_env == 'production'

  - name: install the project's gems for deployment
    bundler:
      chdir: "{{ deploy_dir }}"
      gem_path: "vendor/bundle"
      deployment_mode: "{{ deployment_mode }}"
      exclude_groups: "{{ exclude | default(omit) }}"

  - name: Configure database
    no_log: "{{ not debugging }}"
    template:
      src:  "templates/dotenv.j2"
      dest:  "{{ deploy_dir }}/.env"
    notify: restart apache

  # TODO: refactor
  handlers:
  - name: restart apache
    service:
      name: "{{ apache_service }}"
      enabled: true
      state: restarted
    become: true
