---
- name: check servers with cucumber
  hosts: all
  connection: local

  tasks:
  - name: set variables for tests
    template:
      src: templates/test_vars.rb
      dest: "../features/support/test_vars.rb"
      force: true

  # - name: set environment for tests
  #   template:
  #     src: templates/env.rb.j2
  #     dest: "../features/support/env.rb"
  #     force: true

  - name: test cucumber vars
    command: "bundle exec cucumber features/test_vars.feature"
    args:
      # NOTE: the features are found one level above this playbook
      chdir: "../"

  - name: run cucumber
    command: "bundle exec cucumber"
    args:
      # NOTE: the features are found one level above this playbook
      chdir: "../"
