---
- name: install catalyst services - pull-reserves
  hosts: pull-reserves
  tags:
    - services
    - pull-reserves

  tasks:
  - include_role:
      name: local.service
    vars:
      service_app_name:         "{{ pull_reserves_app_name }}"
      service_app_user:         "{{ app_user }}"
      service_app_repo:         "{{ pull_reserves_app_repo }}"
      service_cron_minute:      "{{ pull_reserves_cron_minute }}"
      service_cron_hour:        "{{ pull_reserves_cron_hour }}"
      service_cron_command:     "{{ pull_reserves_cron_command }}"
      service_config_files:     "{{ pull_reserves_config_files }}"
