---
- name: test {{ item }}
  set_fact:
    ruby_command: "{{ item | regex_replace('-((\\d)+(\\.)*)*', '')}}"
- set_fact:
    ruby_version: "{{ item | regex_replace('^(\\w)+-*', '')}}"
- debug:
    msg: "{{ item }} - ruby_command: {{ ruby_command }} ; ruby_version: {{ ruby_version }}"
